name: Model Comparison Test

on:
  push:
    branches:
      - main # mainブランチへのpush時に実行
  pull_request:
    branches:
      - main # mainブランチへのpull request時にも実行

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11' # プロジェクトで使用しているPythonバージョンに合わせてください

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # requirements.txtのパスを修正 (プロジェクトルートからの相対パス)
          # day1/lecture-ai-engineering/day5/requirements.txt を想定
          # もしday5ディレクトリ直下にrequirements.txtがない場合は、適切なパスに変更してください。
          # ここでは、day1/lecture-ai-engineering/day5/requirements.txt を使用します。
          if [ -f day1/lecture-ai-engineering/day5/requirements.txt ]; then
            pip install -r day1/lecture-ai-engineering/day5/requirements.txt
          else
            echo "requirements.txt not found at day1/lecture-ai-engineering/day5/requirements.txt"
            # 必要なライブラリを直接インストール (例)
            pip install pandas scikit-learn pytest great-expectations mlflow
          fi
          pip install pytest # pytestを明示的にインストール

      - name: Run model comparison tests
        run: |
          # pytestコマンドの実行ディレクトリと対象ディレクトリを指定
          # プロジェクトのルートディレクトリからテストを実行し、
          # day1/lecture-ai-engineering/day5/演習3/tests をテスト対象とする
          pytest day1/lecture-ai-engineering/day5/演習3/tests
